apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./docker-compose.yml --build local -o ../kubernetes/./backend/
    kompose.service.healthcheck.readiness.tcp_port: "5672"
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: rmq
  name: rmq
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rmq
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./docker-compose.yml --build local -o ../kubernetes/./backend/
        kompose.service.healthcheck.readiness.tcp_port: "5672"
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: rmq
    spec:
      containers:
        - env:
            - name: RABBITMQ_DEFAULT_PASS
              value: guest
            - name: RABBITMQ_DEFAULT_USER
              value: guest
            - name: RABBITMQ_DEFAULT_VHOST
              value: /
          image: rabbitmq:3.9.16-alpine
          name: rmq
          ports:
            - containerPort: 5672
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 5672
      hostname: rmq
      restartPolicy: Always
