apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./docker-compose.yml --build local -o ../kubernetes/./backend/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: rmq
  name: rmq
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rmq
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./docker-compose.yml --build local -o ../kubernetes/./backend/
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: rmq
    spec:
      containers:
        - env:
            - name: RABBITMQ_DEFAULT_PASS
              value: guest
            - name: RABBITMQ_DEFAULT_USER
              value: guest
            - name: RABBITMQ_DEFAULT_VHOST
              value: /
          image: rabbitmq:3.9.16-alpine
          livenessProbe:
            exec:
              command:
                - rabbitmq-diagnostics check_running -q
            failureThreshold: 50
            periodSeconds: 3
            timeoutSeconds: 3
          name: rmq
          ports:
            - containerPort: 5672
              protocol: TCP
      hostname: rmq
      restartPolicy: Always
