apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./docker-compose.yml --build local -o ../kubernetes/./broadcast-backend/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: broadcast-backend-api
  name: broadcast-backend-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: broadcast-backend-api
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./docker-compose.yml --build local -o ../kubernetes/./broadcast-backend/
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: broadcast-backend-api
    spec:
      containers:
        - env:
            - name: APP_DB_BASE
              value: app
            - name: APP_DB_HOST
              value: db.backend.svc.cluster.local
            - name: APP_DB_PASS
              value: app
            - name: APP_DB_PORT
              value: "5432"
            - name: APP_DB_USER
              value: app
            - name: APP_ENABLE_SQLITE
              value: "false"
            - name: APP_ENABLE_TASKIQ
              value: "false"
            - name: APP_HOST
              value: 0.0.0.0
          image: qazer25/iot-broadcast-backend:latest
          name: broadcast-backend-api
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
